#Save model using pickle

In [2]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [6]:
hiring_data = {
    'experience': ['zero','zero', 'five', 'two', 'seven', 'three', 'ten', 'eleven'],
    'test_score': [8, 8, 6, 10, 9, 7, None, 7],
    'interview_score': [9, 6, 7, 10, 6, 10, 7, 8],
    'salary': [50000, 45000, 60000, 65000, 70000, 62000, 72000, 80000]
}
df=pd.DataFrame(hiring_data)
from word2number import w2n
import math
df.test_score = df.test_score.fillna(math.floor(df['test_score'].mean()))
df.experience = df.experience.apply(w2n.word_to_num)
df

experience  test_score  interview_score  salary
0           0         8.0                9   50000
1           0         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         7.0                7   72000
7          11         7.0                8   80000

In [10]:
model=linear_model.LinearRegression()
X=df.drop(columns='salary')
model.fit(X,df.salary)
model.predict([[4,10,10]])

d:\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([70369.64416634])

In [12]:
import pickle
with open('hiring_model','wb') as file:
    pickle.dump(model,file)

In [16]:
with open('hiring_model','rb')as file:
    mp=pickle.load(file)

In [18]:
mp.predict([[4,10,10]])

d:\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([70369.64416634])

In [26]:
import joblib
joblib.dump(model,'jl_model')

['jl_model']

In [28]:
jlm=joblib.load('jl_model')
jlm.predict([[4,10,10]])

d:\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([70369.64416634])